select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_count) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_count
from customer
where discount = 'yes' and purchase_count >= (select AVG(purchase_count) from customer)


--Q3. Which are the top 5 products with the highest average review rating?
select customer.item_purchase, AVG(review_rating) as "Average Product Rating"
from customer
group by customer.item_purchase
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT
    shipping_type,
	ROUND(AVG(customer.purchase_count), 2) AS
average_spend
FROM customer
GROUP BY shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue
--between subscribers and non-subscribers.
select subscription,
COUNT("customer_id") as "total customers",
ROUND(AVG(purchase_count), 2) as avg_spend,
ROUND(SUM(purchase_count), 2) as total_revenue
from customer
group by subscription
order by total_revenue, avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchase,
ROUND(SUM(CASE WHEN discount = 'Yes' THEN 1 ELSE 0 END)::NUMERIC / COUNT(*) * 100, 2) as discount_rate
FROM customer
GROUP BY item_purchase
ORDER BY discount_rate DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total
--number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_page,
CASE
    WHEN previous_page = 1 THEN 'New'
	WHEN previous_page BETWEEN 2 AND 10 THEN 'Returning'
	END AS customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment


--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchase,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchase
)

select item_rank, category, item_purchase, total_orders
from item_counts
where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more then 5 previous purchases) also likely to subscribe? 
select subscription,
count(customer_id) as repeat_buyers
from customer
where previous_page > 5
group by subscription


--Q10. What is the revenue contribution of each age group?
select age_group, 
SUM(purchase_count) as total_revenue
from customer
group by age_group
order by total_revenue desc;